sudo: required
services:
  - docker

before_install:
  - docker build -t v1c70r/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run v1c70r/react-test npm test -- --coverage

after_success:
  - docker build -t v1c70r/multi-client ./client
  - docker build -t v1c70r/multi-nginx ./nginx
  - docker build -t v1c70r/multi-server ./server
  - docker build -t v1c70r/multi-worker ./worker
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  - docker push v1c70r/multi-client
  - docker push v1c70r/multi-nginx
  - docker push v1c70r/multi-server
  - docker push v1c70r/multi-worker
